language: java
sudo: false
script: mvn clean verify

jdk:
  - oraclejdk8

before_install:
  - export MAVEN_OPTS="-Xmx2g $MAVEN_OPTS"
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

env:
  global:
    - JAVA_OPTS="-Xmx2g"
